use chrono::{Duration, TimeZone, Utc};
use mycel_core::{
    Antibody, AntibodySource, Confidence, RefusalMode, Severity, Signature, SignatureScope,
    SubstratePaths, SubstrateRuntime,
};
use uuid::Uuid;

fn antibody(tool: &str, remediation: &str) -> Antibody {
    Antibody {
        id: Uuid::new_v4(),
        signature: Signature {
            error_class: None,
            file_pattern: None,
            agent_role: None,
            tool_pattern: Some(tool.to_string()),
            scope: SignatureScope::Project,
        },
        source: AntibodySource::Manual,
        severity: Severity::Warn,
        confidence: Confidence::Solid,
        refusal_mode: RefusalMode::Soft,
        remediation: remediation.to_string(),
        examples: vec!["fixture".to_string()],
        created_at: Utc.with_ymd_and_hms(2026, 5, 28, 8, 0, 0).unwrap(),
        expires_at: None,
        hit_count: 0,
    }
}

fn runtime(dir: &tempfile::TempDir, audit_max_bytes: u64) -> SubstrateRuntime {
    SubstrateRuntime::open(SubstratePaths {
        db_path: dir.path().join("mycel.sqlite"),
        workspace_dir: dir.path().join("workspace"),
        audit_log_path: dir.path().join("audit").join("mycel.jsonl"),
        audit_max_bytes,
    })
    .expect("open runtime")
}

#[test]
fn mutation_audits_immediately_and_regenerates_projection_after_debounce() {
    let dir = tempfile::tempdir().expect("tempdir");
    let mut runtime = runtime(&dir, 1024 * 1024);
    let now = Utc.with_ymd_and_hms(2026, 5, 28, 9, 0, 0).unwrap();
    let antibody = antibody("cargo", "inspect cargo failure before retrying");

    runtime
        .insert_antibody(&antibody, now)
        .expect("insert antibody");

    let audit =
        std::fs::read_to_string(dir.path().join("audit").join("mycel.jsonl")).expect("audit log");
    assert!(audit.contains(r#""event_type":"antibody.inserted""#));
    assert!(audit.contains(&antibody.id.to_string()));
    assert!(!dir.path().join("workspace").join("SUBSTRATE.md").exists());

    runtime
        .flush_projections(now + Duration::milliseconds(499))
        .expect("flush before debounce");
    assert!(!dir.path().join("workspace").join("SUBSTRATE.md").exists());

    runtime
        .flush_projections(now + Duration::milliseconds(500))
        .expect("flush after debounce");
    let projection = std::fs::read_to_string(dir.path().join("workspace").join("SUBSTRATE.md"))
        .expect("projection");

    assert!(projection.starts_with(
        "<!-- generated by Mycel; projection only; not an input surface. do not edit. -->"
    ));
    assert!(projection.contains("# substrate"));
    assert!(projection.contains("cargo"));
    assert!(projection.contains("inspect cargo failure before retrying"));
}

#[test]
fn projection_output_is_deterministic() {
    let dir = tempfile::tempdir().expect("tempdir");
    let mut runtime = runtime(&dir, 1024 * 1024);
    let now = Utc.with_ymd_and_hms(2026, 5, 28, 9, 0, 0).unwrap();

    runtime
        .insert_antibody(&antibody("cargo", "first"), now)
        .expect("insert first");
    runtime
        .insert_antibody(
            &antibody("shell", "second"),
            now + Duration::milliseconds(100),
        )
        .expect("insert second");
    runtime
        .flush_projections(now + Duration::milliseconds(600))
        .expect("flush projection");
    let first = std::fs::read_to_string(dir.path().join("workspace").join("SUBSTRATE.md"))
        .expect("first projection");

    runtime
        .flush_projections(now + Duration::seconds(2))
        .expect("flush again");
    let second = std::fs::read_to_string(dir.path().join("workspace").join("SUBSTRATE.md"))
        .expect("second projection");

    assert_eq!(first, second);
}

#[test]
fn insert_update_and_delete_all_emit_audit_events() {
    let dir = tempfile::tempdir().expect("tempdir");
    let mut runtime = runtime(&dir, 1024 * 1024);
    let now = Utc.with_ymd_and_hms(2026, 5, 28, 9, 0, 0).unwrap();
    let mut antibody = antibody("cargo", "first");

    runtime
        .insert_antibody(&antibody, now)
        .expect("insert antibody");
    antibody.remediation = "second".to_string();
    runtime
        .update_antibody(&antibody, now + Duration::milliseconds(1))
        .expect("update antibody");
    runtime
        .delete_antibody(antibody.id, now + Duration::milliseconds(2))
        .expect("delete antibody");

    let audit =
        std::fs::read_to_string(dir.path().join("audit").join("mycel.jsonl")).expect("audit log");
    assert_eq!(audit.lines().count(), 3);
    assert!(audit.contains(r#""event_type":"antibody.inserted""#));
    assert!(audit.contains(r#""event_type":"antibody.updated""#));
    assert!(audit.contains(r#""event_type":"antibody.deleted""#));
}

#[test]
fn audit_log_rotates_when_size_limit_is_reached() {
    let dir = tempfile::tempdir().expect("tempdir");
    let mut runtime = runtime(&dir, 180);
    let now = Utc.with_ymd_and_hms(2026, 5, 28, 9, 0, 0).unwrap();

    for index in 0..4 {
        runtime
            .insert_antibody(
                &antibody(&format!("tool-{index}"), "rotation fixture"),
                now + Duration::milliseconds(index),
            )
            .expect("insert antibody");
    }

    let audit_dir = dir.path().join("audit");
    assert!(audit_dir.join("mycel.1.jsonl").exists());
    assert!(audit_dir.join("mycel.jsonl").exists());
}
