//! Deterministic workspace projections over the run substrate.
//!
//! Two renderers:
//! - `render_substrate_md` — live / retained / preserved runs.
//! - `render_compost_md` — distilled (gist kept) / decayed (tombstone only) runs.
//!
//! Both take `&[Run]` and return `String`. Determinism is load-bearing: rows are
//! stable-sorted by `(created_at, id)` within each section, and no generation
//! timestamp appears in the body. See ADR 0011.
//!
//! `run_maintenance` applies decay, renders both files into a workspace directory,
//! and appends a `maintenance` audit event.

use std::{fs, path::Path, path::PathBuf};

use serde::Serialize;

use crate::{AuditLog, Confidence, Db, DecayEngine, DecayReport, Run, Substrate};

// ── helpers ───────────────────────────────────────────────────────────────────

const HEADER: &str =
    "<!-- generated by Mycel; projection only; not an input surface. do not edit. -->\n";

fn escape_cell(value: &str) -> String {
    value.replace('|', "\\|").replace('\n', " ")
}

fn confidence_str(c: Confidence) -> &'static str {
    match c {
        Confidence::Solid => "solid",
        Confidence::Directional => "directional",
        Confidence::Vibes => "vibes",
    }
}

/// Sort runs deterministically: primary key `created_at`, secondary key `id` (lexicographic).
fn sort_runs(runs: &mut Vec<&Run>) {
    runs.sort_by(|a, b| a.created_at.cmp(&b.created_at).then(a.id.cmp(&b.id)));
}

// ── SUBSTRATE.md ──────────────────────────────────────────────────────────────

/// Render `SUBSTRATE.md` — active substrate snapshot.
///
/// Sections:
/// - `## live` — runs with `decay_state IS NULL` and `no_compost = false`.
/// - `## retained` — runs with `decay_state == "retained"`.
/// - `## preserved` — runs with `no_compost = true` (regardless of decay_state).
///
/// Each section is a markdown table `| id | kind | confidence | summary |`.
/// Empty section → `none`. Rows are stable-sorted by `(created_at, id)`.
pub fn render_substrate_md(runs: &[Run]) -> String {
    let mut output = format!("{HEADER}# substrate\n\n");

    // live: no decay_state yet and not no_compost
    let mut live: Vec<&Run> = runs
        .iter()
        .filter(|r| r.decay_state.is_none() && !r.no_compost)
        .collect();
    sort_runs(&mut live);

    // retained: decay_state == "retained"
    let mut retained: Vec<&Run> = runs
        .iter()
        .filter(|r| r.decay_state.as_deref() == Some("retained"))
        .collect();
    sort_runs(&mut retained);

    // preserved: no_compost == true
    let mut preserved: Vec<&Run> = runs.iter().filter(|r| r.no_compost).collect();
    sort_runs(&mut preserved);

    output.push_str("## live\n\n");
    write_substrate_section(&mut output, &live);

    output.push_str("\n## retained\n\n");
    write_substrate_section(&mut output, &retained);

    output.push_str("\n## preserved\n\n");
    write_substrate_section(&mut output, &preserved);

    output
}

fn write_substrate_section(output: &mut String, runs: &[&Run]) {
    if runs.is_empty() {
        output.push_str("none\n");
        return;
    }
    output.push_str("| id | kind | confidence | summary |\n");
    output.push_str("| --- | --- | --- | --- |\n");
    for run in runs {
        output.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            run.id,
            run.kind.as_str(),
            confidence_str(run.confidence),
            escape_cell(&run.summary),
        ));
    }
}

// ── COMPOST.md ────────────────────────────────────────────────────────────────

/// Render `COMPOST.md` — post-decay tombstone record.
///
/// Sections:
/// - `## distilled` — runs with `decay_state == "distilled"`; shows `distilled_summary`.
/// - `## decayed` — runs with `decay_state == "decayed"`; tombstone only (id + confidence).
///
/// Empty section → `none`. Rows are stable-sorted by `(created_at, id)`.
pub fn render_compost_md(runs: &[Run]) -> String {
    let mut output = format!("{HEADER}# compost\n\n");

    let mut distilled: Vec<&Run> = runs
        .iter()
        .filter(|r| r.decay_state.as_deref() == Some("distilled"))
        .collect();
    sort_runs(&mut distilled);

    let mut decayed: Vec<&Run> = runs
        .iter()
        .filter(|r| r.decay_state.as_deref() == Some("decayed"))
        .collect();
    sort_runs(&mut decayed);

    output.push_str("## distilled\n\n");
    if distilled.is_empty() {
        output.push_str("none\n");
    } else {
        output.push_str("| id | confidence | distilled |\n");
        output.push_str("| --- | --- | --- |\n");
        for run in &distilled {
            let gist = run
                .distilled_summary
                .as_deref()
                .unwrap_or("")
                .replace('|', "\\|")
                .replace('\n', " ");
            output.push_str(&format!(
                "| {} | {} | {} |\n",
                run.id,
                confidence_str(run.confidence),
                gist,
            ));
        }
    }

    output.push_str("\n## decayed\n\n");
    if decayed.is_empty() {
        output.push_str("none\n");
    } else {
        output.push_str("| id | confidence |\n");
        output.push_str("| --- | --- |\n");
        for run in &decayed {
            output.push_str(&format!(
                "| {} | {} |\n",
                run.id,
                confidence_str(run.confidence),
            ));
        }
    }

    output
}

// ── maintenance cycle ─────────────────────────────────────────────────────────

/// Outcome of a single `run_maintenance` call.
pub struct MaintenanceReport {
    pub decay: DecayReport,
    pub substrate_path: PathBuf,
    pub compost_path: PathBuf,
}

/// Run one scheduled maintenance cycle as of unix timestamp `now`.
///
/// Order of operations:
/// 1. Apply decay via `DecayEngine`.
/// 2. List all runs (now with updated decay_state).
/// 3. Render `SUBSTRATE.md` and `COMPOST.md`.
/// 4. Write both files into `workspace_dir`.
/// 5. Append a `maintenance` audit event with decay counts.
///
/// Deterministic and idempotent (decay engine is idempotent; renderers are pure).
pub fn run_maintenance(
    db: &Db,
    workspace_dir: &Path,
    now: i64,
) -> crate::Result<MaintenanceReport> {
    // 1. Apply decay.
    let decay = DecayEngine::new(db).run(now)?;

    // 2. List runs after decay so decay_state is current.
    let runs = Substrate::new(db).list()?;

    // 3+4. Render and write.
    fs::create_dir_all(workspace_dir)?;

    let substrate_path = workspace_dir.join("SUBSTRATE.md");
    let compost_path = workspace_dir.join("COMPOST.md");

    fs::write(&substrate_path, render_substrate_md(&runs))?;
    fs::write(&compost_path, render_compost_md(&runs))?;

    // 5. Audit.
    let payload = MaintenanceAuditPayload {
        now,
        retained: decay.retained.len(),
        distilled: decay.distilled.len(),
        decayed: decay.decayed.len(),
        preserved: decay.preserved.len(),
        skipped_live: decay.skipped_live.len(),
    };
    AuditLog::new(db).append("maintenance", &payload)?;

    Ok(MaintenanceReport {
        decay,
        substrate_path,
        compost_path,
    })
}

#[derive(Serialize)]
struct MaintenanceAuditPayload {
    now: i64,
    retained: usize,
    distilled: usize,
    decayed: usize,
    preserved: usize,
    skipped_live: usize,
}

// ── tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Confidence, Db, RunKind, RunStatus, Substrate};

    fn test_db() -> Db {
        Db::open_in_memory().expect("open in-memory db")
    }

    /// Build a `Run` with all fields filled deterministically (no DB, no UUID randomness).
    #[allow(clippy::too_many_arguments)]
    fn make_run(
        id: &str,
        kind: RunKind,
        confidence: Confidence,
        summary: &str,
        created_at: i64,
        no_compost: bool,
        decay_state: Option<&str>,
        distilled_summary: Option<&str>,
    ) -> Run {
        Run {
            id: id.to_string(),
            kind,
            status: RunStatus::Applied,
            summary: summary.to_string(),
            confidence,
            created_at,
            expires_at: None,
            no_compost,
            decay_state: decay_state.map(str::to_string),
            decayed_at: None,
            distilled_summary: distilled_summary.map(str::to_string),
        }
    }

    // ── determinism: same input different order → identical output ────────────

    #[test]
    fn render_substrate_md_is_deterministic_regardless_of_insert_order() {
        let live_a = make_run(
            "aaa-live",
            RunKind::Observation,
            Confidence::Solid,
            "live run A",
            1000,
            false,
            None,
            None,
        );
        let live_b = make_run(
            "bbb-live",
            RunKind::Mutation,
            Confidence::Directional,
            "live run B",
            2000,
            false,
            None,
            None,
        );
        let retained = make_run(
            "ccc-retained",
            RunKind::Observation,
            Confidence::Solid,
            "retained run",
            500,
            false,
            Some("retained"),
            None,
        );

        let order1 = vec![live_a.clone(), live_b.clone(), retained.clone()];
        let order2 = vec![retained.clone(), live_b.clone(), live_a.clone()];

        assert_eq!(
            render_substrate_md(&order1),
            render_substrate_md(&order2),
            "substrate render must be deterministic regardless of input order"
        );
    }

    #[test]
    fn render_compost_md_is_deterministic_regardless_of_insert_order() {
        let distilled = make_run(
            "aaa-dist",
            RunKind::Observation,
            Confidence::Directional,
            "original long summary",
            1000,
            false,
            Some("distilled"),
            Some("short gist"),
        );
        let decayed = make_run(
            "bbb-decayed",
            RunKind::Observation,
            Confidence::Vibes,
            "noisy hypothesis",
            2000,
            false,
            Some("decayed"),
            None,
        );

        let order1 = vec![distilled.clone(), decayed.clone()];
        let order2 = vec![decayed.clone(), distilled.clone()];

        assert_eq!(
            render_compost_md(&order1),
            render_compost_md(&order2),
            "compost render must be deterministic regardless of input order"
        );
    }

    // ── render twice → byte-identical ────────────────────────────────────────

    #[test]
    fn render_substrate_md_is_byte_identical_on_repeated_call() {
        let run = make_run(
            "zzz-live",
            RunKind::Task,
            Confidence::Solid,
            "a live task",
            9999,
            false,
            None,
            None,
        );
        let runs = vec![run];
        assert_eq!(render_substrate_md(&runs), render_substrate_md(&runs));
    }

    // ── placement: live section ───────────────────────────────────────────────

    #[test]
    fn live_run_appears_under_live_section() {
        let run = make_run(
            "live-id",
            RunKind::Observation,
            Confidence::Directional,
            "a live observation",
            100,
            false,
            None,
            None,
        );
        let md = render_substrate_md(&[run]);
        // Must appear under ## live
        let live_section = section_body(&md, "## live");
        assert!(
            live_section.contains("live-id"),
            "live run id must appear under ## live\n---\n{md}"
        );
        // Must NOT appear under ## retained or ## preserved
        let retained_section = section_body(&md, "## retained");
        assert!(
            !retained_section.contains("live-id"),
            "live run must not appear under ## retained"
        );
        let preserved_section = section_body(&md, "## preserved");
        assert!(
            !preserved_section.contains("live-id"),
            "live run must not appear under ## preserved"
        );
    }

    #[test]
    fn retained_run_appears_under_retained_section_only() {
        let run = make_run(
            "ret-id",
            RunKind::Observation,
            Confidence::Solid,
            "solid retained run",
            100,
            false,
            Some("retained"),
            None,
        );
        let md = render_substrate_md(&[run]);
        assert!(
            section_body(&md, "## retained").contains("ret-id"),
            "retained run must appear under ## retained\n---\n{md}"
        );
        assert!(
            !section_body(&md, "## live").contains("ret-id"),
            "retained run must not appear under ## live"
        );
    }

    #[test]
    fn preserved_run_appears_under_preserved_section() {
        let run = make_run(
            "pres-id",
            RunKind::Observation,
            Confidence::Solid,
            "no_compost run",
            100,
            true, // no_compost
            None,
            None,
        );
        let md = render_substrate_md(&[run]);
        assert!(
            section_body(&md, "## preserved").contains("pres-id"),
            "no_compost run must appear under ## preserved\n---\n{md}"
        );
    }

    #[test]
    fn decayed_run_does_not_appear_in_substrate_md() {
        let run = make_run(
            "decay-id",
            RunKind::Observation,
            Confidence::Vibes,
            "vibes hypothesis",
            100,
            false,
            Some("decayed"),
            None,
        );
        let md = render_substrate_md(&[run]);
        assert!(
            !md.contains("decay-id"),
            "decayed run must not appear in SUBSTRATE.md\n---\n{md}"
        );
    }

    // ── placement: compost sections ───────────────────────────────────────────

    #[test]
    fn distilled_run_appears_with_distilled_summary_not_original() {
        let original_summary = "a very long original summary that should not appear in compost";
        let gist = "short gist";
        let run = make_run(
            "dist-id",
            RunKind::Observation,
            Confidence::Directional,
            original_summary,
            100,
            false,
            Some("distilled"),
            Some(gist),
        );
        let md = render_compost_md(&[run]);
        let distilled_section = section_body(&md, "## distilled");
        assert!(
            distilled_section.contains("dist-id"),
            "distilled run must appear under ## distilled\n---\n{md}"
        );
        assert!(
            distilled_section.contains(gist),
            "distilled section must contain the distilled_summary gist\n---\n{md}"
        );
        // The original summary must NOT appear in compost
        assert!(
            !md.contains(original_summary),
            "original summary must not appear in COMPOST.md\n---\n{md}"
        );
    }

    #[test]
    fn decayed_run_appears_as_tombstone_original_summary_absent() {
        let original_summary = "unique-vibes-hypothesis-text-xyz";
        let run = make_run(
            "tomb-id",
            RunKind::Observation,
            Confidence::Vibes,
            original_summary,
            100,
            false,
            Some("decayed"),
            None,
        );
        let md = render_compost_md(&[run]);
        let decayed_section = section_body(&md, "## decayed");
        assert!(
            decayed_section.contains("tomb-id"),
            "decayed run id must appear under ## decayed (tombstone)\n---\n{md}"
        );
        assert!(
            !md.contains(original_summary),
            "original summary must NOT appear in COMPOST.md (tombstone only)\n---\n{md}"
        );
    }

    #[test]
    fn live_run_does_not_appear_in_compost_md() {
        let run = make_run(
            "live-compost-id",
            RunKind::Observation,
            Confidence::Solid,
            "a live run",
            100,
            false,
            None,
            None,
        );
        let md = render_compost_md(&[run]);
        assert!(
            !md.contains("live-compost-id"),
            "live run must not appear in COMPOST.md\n---\n{md}"
        );
    }

    // ── empty sections render 'none' ──────────────────────────────────────────

    #[test]
    fn empty_substrate_sections_render_none() {
        let md = render_substrate_md(&[]);
        assert!(
            md.contains("## live\n\nnone"),
            "empty live should render none"
        );
        assert!(
            md.contains("## retained\n\nnone"),
            "empty retained should render none"
        );
        assert!(
            md.contains("## preserved\n\nnone"),
            "empty preserved should render none"
        );
    }

    #[test]
    fn empty_compost_sections_render_none() {
        let md = render_compost_md(&[]);
        assert!(
            md.contains("## distilled\n\nnone"),
            "empty distilled should render none"
        );
        assert!(
            md.contains("## decayed\n\nnone"),
            "empty decayed should render none"
        );
    }

    // ── run_maintenance integration ───────────────────────────────────────────

    #[test]
    fn run_maintenance_writes_files_and_appends_audit_event() {
        let db = test_db();
        let sub = Substrate::new(&db);

        // Insert a speculative (Vibes) record with TTL 500 → expires at 500.
        sub.insert_with_decay(
            RunKind::Observation,
            RunStatus::Applied,
            "speculative hypothesis for maintenance test",
            Confidence::Vibes,
            Some(500),
            false,
        )
        .expect("insert vibes");

        // Insert a directional (Directional) record with TTL 500.
        sub.insert_with_decay(
            RunKind::Observation,
            RunStatus::Applied,
            "probable observation for maintenance test",
            Confidence::Directional,
            Some(500),
            false,
        )
        .expect("insert directional");

        // Use a temp dir for workspace.
        let workspace = tempfile::tempdir().expect("tempdir");

        // Run maintenance at now=1000 → both runs are expired.
        let report = run_maintenance(&db, workspace.path(), 1000).expect("run_maintenance");

        // Both files must exist.
        assert!(
            report.substrate_path.exists(),
            "SUBSTRATE.md must exist after maintenance"
        );
        assert!(
            report.compost_path.exists(),
            "COMPOST.md must exist after maintenance"
        );

        // SUBSTRATE.md must have the header.
        let substrate_md = fs::read_to_string(&report.substrate_path).expect("read SUBSTRATE.md");
        assert!(
            substrate_md.starts_with("<!-- generated by Mycel"),
            "SUBSTRATE.md must have generated header"
        );
        assert!(
            substrate_md.contains("# substrate"),
            "SUBSTRATE.md must contain # substrate heading"
        );

        // COMPOST.md must have distilled and decayed sections populated.
        let compost_md = fs::read_to_string(&report.compost_path).expect("read COMPOST.md");
        assert!(
            compost_md.contains("## distilled"),
            "COMPOST.md must have ## distilled section"
        );
        assert!(
            compost_md.contains("## decayed"),
            "COMPOST.md must have ## decayed section"
        );

        // Audit log must contain a maintenance event.
        let log = AuditLog::new(&db).list().expect("audit list");
        let maintenance_events: Vec<_> = log.iter().filter(|e| e.event == "maintenance").collect();
        assert!(
            !maintenance_events.is_empty(),
            "audit log must contain a maintenance event"
        );

        let payload = &maintenance_events[0].payload;
        assert_eq!(
            payload.get("now").and_then(|v| v.as_i64()),
            Some(1000),
            "maintenance audit payload must record the now timestamp"
        );
        // distilled from 1 directional + decayed from 1 vibes
        assert_eq!(
            payload.get("distilled").and_then(|v| v.as_u64()),
            Some(1),
            "maintenance audit payload must record distilled count"
        );
        assert_eq!(
            payload.get("decayed").and_then(|v| v.as_u64()),
            Some(1),
            "maintenance audit payload must record decayed count"
        );
    }

    // ── helper: extract text from ## heading to next ## or EOF ───────────────

    fn section_body<'a>(md: &'a str, heading: &str) -> &'a str {
        let start = match md.find(heading) {
            Some(pos) => pos + heading.len(),
            None => return "",
        };
        let rest = &md[start..];
        // Find the next ## section (but not the current heading's newline)
        let end = rest[1..]
            .find("\n## ")
            .map(|pos| pos + 1) // offset for the skipped char
            .unwrap_or(rest.len());
        &rest[..end]
    }
}
