//! PromptPressure integration: tier import → Mycel run substrate.
//!
//! PromptPressure is an external confidence-tier input for context decay.
//! This module maps each PromptPressure tier to a Mycel `Confidence` and a
//! TTL, and durably records the original tier in the audit log so the mapping
//! is auditable and reversible.
//!
//! ## Tier → Confidence mapping
//!
//! | PromptPressure tier | Mycel Confidence |
//! | --- | --- |
//! | `Verified` | `Solid` |
//! | `Probable` | `Directional` |
//! | `Speculative` | `Vibes` |
//!
//! ## Tier → TTL policy
//!
//! | tier | ttl | rationale |
//! | --- | --- | --- |
//! | `Speculative` | 7 days | short-lived hypotheses; high noise, prune aggressively |
//! | `Probable` | 30 days | shaped-right findings; useful window for a sprint cycle |
//! | `Verified` | 365 days | verified facts; long-term substrate material |
//!
//! ## Label fidelity (load-bearing)
//!
//! The original PromptPressure tier string is preserved in the `audit_log`
//! table under event `"promptpressure_import"` so the mapping from tier to
//! confidence is auditable. This satisfies the ROADMAP rollback condition:
//! "if tier import loses confidence labels, PromptPressure integration stays
//! experimental." See ADR 0010.

use serde::{Deserialize, Serialize};

use crate::{AuditLog, Confidence, Db, RunKind, RunStatus, Substrate};

// ── TTL constants (seconds) ───────────────────────────────────────────────────

/// Speculative tier: 7 days. Hypotheses are high-noise; prune aggressively.
pub const TTL_SPECULATIVE: i64 = 7 * 24 * 60 * 60;
/// Probable tier: 30 days. Useful across a typical sprint cycle.
pub const TTL_PROBABLE: i64 = 30 * 24 * 60 * 60;
/// Verified tier: 365 days. Long-term substrate material.
pub const TTL_VERIFIED: i64 = 365 * 24 * 60 * 60;

// ── wire record ───────────────────────────────────────────────────────────────

/// A confidence-tier record as emitted by PromptPressure.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PromptPressureRecord {
    /// Stable identity of the source note/finding in PromptPressure.
    pub source_id: String,
    /// PromptPressure confidence tier label, verbatim from the source.
    pub tier: PromptPressureTier,
    /// The note/finding text.
    pub summary: String,
}

/// PromptPressure confidence tier labels.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PromptPressureTier {
    /// Verified / high-confidence → maps to Mycel `Solid`.
    Verified,
    /// Probable / shaped-right → maps to Mycel `Directional`.
    Probable,
    /// Speculative / hypothesis → maps to Mycel `Vibes`.
    Speculative,
}

impl PromptPressureTier {
    /// Map this tier to the corresponding Mycel `Confidence`.
    ///
    /// Mapping: Verified→Solid, Probable→Directional, Speculative→Vibes.
    pub fn to_confidence(self) -> Confidence {
        match self {
            Self::Verified => Confidence::Solid,
            Self::Probable => Confidence::Directional,
            Self::Speculative => Confidence::Vibes,
        }
    }

    /// Return the snake_case string representation used in serde and audit
    /// payloads.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Verified => "verified",
            Self::Probable => "probable",
            Self::Speculative => "speculative",
        }
    }

    /// TTL in seconds for this tier.
    pub fn ttl_seconds(self) -> i64 {
        match self {
            Self::Speculative => TTL_SPECULATIVE,
            Self::Probable => TTL_PROBABLE,
            Self::Verified => TTL_VERIFIED,
        }
    }
}

// ── helpers ───────────────────────────────────────────────────────────────────

/// Return the string representation of a `Confidence` value.
///
/// Mirrors the `string_enum!` mapping in `lib.rs` without requiring access to
/// the private `as_str` generated by that macro.
fn confidence_as_str(c: Confidence) -> &'static str {
    match c {
        Confidence::Solid => "solid",
        Confidence::Directional => "directional",
        Confidence::Vibes => "vibes",
    }
}

// ── audit payload ─────────────────────────────────────────────────────────────

#[derive(Serialize)]
struct ImportAuditPayload<'a> {
    source_id: &'a str,
    /// Original PromptPressure tier string — the label-fidelity anchor.
    tier: &'a str,
    /// The mapped Mycel confidence string.
    confidence: &'static str,
    run_id: &'a str,
    now: i64,
}

// ── importer ──────────────────────────────────────────────────────────────────

/// Imports PromptPressure records into the Mycel run substrate.
pub struct PromptPressureImport<'a> {
    db: &'a Db,
}

impl<'a> PromptPressureImport<'a> {
    pub fn new(db: &'a Db) -> Self {
        Self { db }
    }

    /// Import one record as of unix timestamp `now`. Returns the new run id.
    ///
    /// The original tier is preserved in the audit log under event
    /// `"promptpressure_import"` — this is the load-bearing label-fidelity
    /// record.
    pub fn import_record(&self, record: &PromptPressureRecord, now: i64) -> crate::Result<String> {
        let confidence = record.tier.to_confidence();
        let expires_at = now + record.tier.ttl_seconds();

        let run_id = Substrate::new(self.db).insert_with_decay(
            RunKind::Observation,
            RunStatus::Applied,
            &record.summary,
            confidence,
            Some(expires_at),
            false,
        )?;

        let payload = ImportAuditPayload {
            source_id: &record.source_id,
            tier: record.tier.as_str(),
            confidence: confidence_as_str(confidence),
            run_id: &run_id,
            now,
        };
        AuditLog::new(self.db).append("promptpressure_import", &payload)?;

        Ok(run_id)
    }

    /// Import a batch of records. Returns the run ids in input order.
    pub fn import_batch(
        &self,
        records: &[PromptPressureRecord],
        now: i64,
    ) -> crate::Result<Vec<String>> {
        records
            .iter()
            .map(|record| self.import_record(record, now))
            .collect()
    }
}

// ── unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AuditLog, Confidence, Db, Substrate};

    fn test_db() -> Db {
        Db::open_in_memory().expect("open in-memory db")
    }

    // ── tier → confidence mapping ─────────────────────────────────────────────

    #[test]
    fn verified_maps_to_solid() {
        assert_eq!(
            PromptPressureTier::Verified.to_confidence(),
            Confidence::Solid
        );
    }

    #[test]
    fn probable_maps_to_directional() {
        assert_eq!(
            PromptPressureTier::Probable.to_confidence(),
            Confidence::Directional
        );
    }

    #[test]
    fn speculative_maps_to_vibes() {
        assert_eq!(
            PromptPressureTier::Speculative.to_confidence(),
            Confidence::Vibes
        );
    }

    // ── import_record label fidelity ──────────────────────────────────────────

    #[test]
    fn import_record_probable_label_fidelity_and_ttl() {
        let db = test_db();
        let now: i64 = 1_000_000;
        let record = PromptPressureRecord {
            source_id: "pp-test-001".to_string(),
            tier: PromptPressureTier::Probable,
            summary: "a probable finding about context window management".to_string(),
        };

        let run_id = PromptPressureImport::new(&db)
            .import_record(&record, now)
            .expect("import_record");

        // Run has confidence == Directional and correct expires_at.
        let run = Substrate::new(&db)
            .get(&run_id)
            .expect("get")
            .expect("must exist");
        assert_eq!(
            run.confidence,
            Confidence::Directional,
            "probable should map to directional"
        );
        assert_eq!(
            run.expires_at,
            Some(now + TTL_PROBABLE),
            "expires_at must be now + TTL_PROBABLE"
        );

        // Audit log contains a promptpressure_import entry with the original
        // tier label and the source_id — label fidelity proof.
        let log = AuditLog::new(&db).list().expect("list");
        let import_events: Vec<_> = log
            .iter()
            .filter(|e| e.event == "promptpressure_import")
            .collect();
        assert!(
            !import_events.is_empty(),
            "audit log must contain a promptpressure_import event"
        );
        let payload = &import_events[0].payload;
        assert_eq!(
            payload.get("tier").and_then(|v| v.as_str()),
            Some("probable"),
            "audit payload must preserve original tier label 'probable'"
        );
        assert_eq!(
            payload.get("source_id").and_then(|v| v.as_str()),
            Some("pp-test-001"),
            "audit payload must include source_id"
        );
        assert_eq!(
            payload.get("run_id").and_then(|v| v.as_str()),
            Some(run_id.as_str()),
            "audit payload must include the run_id"
        );
    }

    // ── import_batch ──────────────────────────────────────────────────────────

    #[test]
    fn import_batch_three_mixed_tiers_returns_correct_confidences() {
        let db = test_db();
        let now: i64 = 2_000_000;
        let records = vec![
            PromptPressureRecord {
                source_id: "pp-batch-001".to_string(),
                tier: PromptPressureTier::Verified,
                summary: "verified finding one".to_string(),
            },
            PromptPressureRecord {
                source_id: "pp-batch-002".to_string(),
                tier: PromptPressureTier::Probable,
                summary: "probable finding two".to_string(),
            },
            PromptPressureRecord {
                source_id: "pp-batch-003".to_string(),
                tier: PromptPressureTier::Speculative,
                summary: "speculative finding three".to_string(),
            },
        ];

        let ids = PromptPressureImport::new(&db)
            .import_batch(&records, now)
            .expect("import_batch");

        assert_eq!(ids.len(), 3, "import_batch must return 3 ids");

        let sub = Substrate::new(&db);
        let expected = [
            Confidence::Solid,
            Confidence::Directional,
            Confidence::Vibes,
        ];
        for (id, exp_conf) in ids.iter().zip(expected.iter()) {
            let run = sub.get(id).expect("get").expect("must exist");
            assert_eq!(
                run.confidence, *exp_conf,
                "run {id} has wrong confidence: got {:?}, want {:?}",
                run.confidence, exp_conf
            );
        }
    }
}
